<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerINImdba\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerINImdba/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerINImdba.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerINImdba\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerINImdba\App_KernelLocalDebugContainer([
    'container.build_hash' => 'INImdba',
    'container.build_id' => '83a9d907',
    'container.build_time' => 1769541679,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerINImdba');
