<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/a-propos']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'gallery' => [[], ['_controller' => 'App\\Controller\\GalleryController::index'], [], [['text', '/galerie']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'legal' => [[], ['_controller' => 'App\\Controller\\LegalController::index'], [], [['text', '/mentions-legales']], [], [], []],
    'prestations' => [[], ['_controller' => 'App\\Controller\\PrestationsController::index'], [], [['text', '/prestations']], [], [], []],
    'rental' => [[], ['_controller' => 'App\\Controller\\RentalController::index'], [], [['text', '/location-materiel']], [], [], []],
    'rental_product' => [['slug'], ['_controller' => 'App\\Controller\\RentalController::product'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/location-materiel']], [], [], []],
    'sitemap' => [[], ['_format' => 'xml', '_controller' => 'App\\Controller\\SitemapController::index'], [], [['text', '/sitemap.xml']], [], [], []],
];
