<?php

namespace ContainerINImdba;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationsControllerService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the public 'App\Controller\PrestationsController' shared autowired service.
     *
     * @return \App\Controller\PrestationsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PrestationsController.php';

        $container->services['App\\Controller\\PrestationsController'] = $instance = new \App\Controller\PrestationsController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\PrestationsController', $container));

        return $instance;
    }
}
