<?php

namespace ContainerEbdA37G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KAr2fsuService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private '.service_locator.KAr2fsu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KAr2fsu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'logger' => ['privates', 'logger', 'getLoggerService', false],
            'rateLimiter' => ['privates', 'App\\Service\\RateLimiterService', 'getRateLimiterServiceService', true],
        ], [
            'em' => '?',
            'emailService' => 'App\\Service\\EmailService',
            'logger' => '?',
            'rateLimiter' => 'App\\Service\\RateLimiterService',
        ]);
    }
}
