<?php

namespace ContainerEbdA37G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRateLimiterServiceService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private 'App\Service\RateLimiterService' shared autowired service.
     *
     * @return \App\Service\RateLimiterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RateLimiterService.php';

        return $container->privates['App\\Service\\RateLimiterService'] = new \App\Service\RateLimiterService(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
