<?php

namespace ContainerJThmeWZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E75p3D2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e75p3D2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e75p3D2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'urlGenerator' => '?',
        ]);
    }
}
