<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJThmeWZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJThmeWZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJThmeWZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJThmeWZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJThmeWZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'JThmeWZ',
    'container.build_id' => '36754bf2',
    'container.build_time' => 1769730996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJThmeWZ');
