<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCo1ibE9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCo1ibE9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCo1ibE9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCo1ibE9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCo1ibE9\App_KernelDevDebugContainer([
    'container.build_hash' => 'Co1ibE9',
    'container.build_id' => '0dad6cb7',
    'container.build_time' => 1768523850,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCo1ibE9');
