<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.1b5762f4.js',
                '/build/528.2a14cd2d.js',
                '/build/app.6940b5c2.js',
            ],
            'css' => [
                '/build/app.8df4fbd7.css',
            ],
        ],
    ],
],

]];
